name: Mirror Repository with Bitbucket

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
          username: MEZ901
          spacename: test-workspace-0001
          repository: bitbucket-pipelines-github-test
          password: ${{ secrets.BITBUCKET_PASSWORD }}
